name: chemcharts
channels:
  - rdkit
  - conda-forge
  - defaults
dependencies:
  - dill
  - jupyter
  - pip
  - plotly>=5.1.0
  - python>=3.8
  - rdkit>=2020.09
  - seaborn>=0.11
  - pip:
    - ffmpeg-python>=0.2.0
    - scikit-learn>=0.24
    - umap-learn
    - kaleido

