name: chemcharts
channels:
  - rdkit
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - anyio=2.1.0=py37h89c1867_0
  - argon2-cffi=20.1.0=py37h5e8e339_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyh44b312d_0
  - brotlipy=0.7.0=py37h5e8e339_1001
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.8=ha878542_0
  - cairo=1.14.12=h8948797_3
  - certifi=2021.10.8=py37h89c1867_0
  - cffi=1.14.4=py37hc58025e_1
  - chardet=4.0.0=py37h89c1867_1
  - cryptography=3.4.4=py37hf1a17b8_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - dill
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.66.1=h92f7085_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.4.0=py37h89c1867_0
  - importlib_metadata=3.4.0=hd8ed1ab_0
  - intel-openmp=2020.2=254
  - ipykernel=5.5.5=py37h085eea5_0
  - ipython=7.20.0=py37h888b3d9_2
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py37h89c1867_2
  - jinja2=2.11.3=pyh44b312d_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.1=py37h89c1867_0
  - jupyter_server=1.3.0=py37h89c1867_0
  - jupyterlab=3.0.7=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.2.0=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py37h2531618_0
  - kneed=0.7.0=pyh9f0ad1d_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.8.0=21_mkl
  - libboost=1.73.0=h3ff78a5_11
  - libcblas=3.8.0=21_mkl
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=9.3.0=h5101ec6_17
  - liblapack=3.8.0=21_mkl
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.3=h2531618_0
  - markupsafe=1.1.1=py37h5e8e339_3
  - matplotlib=3.3.4=py37h89c1867_0
  - matplotlib-base=3.3.4=py37h62a2d02_0
  - mistune=0.8.4=py37h5e8e339_1003
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - nbclassic=0.2.6=pyhd8ed1ab_0
  - nbclient=0.5.2=pyhd8ed1ab_0
  - nbconvert=6.0.7=py37h89c1867_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - notebook=6.2.0=py37h89c1867_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openssl=1.1.1j=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.1=py37ha9443f7_0
  - pandoc=2.11.4=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.1=pyhd8ed1ab_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.0=py37he98fc37_0
  - pip=20.3.3=py37h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - plotly
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.14=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py-boost=1.73.0=py37ha9443f7_11
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.4=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.17.3=py37h5e8e339_2
  - pysocks=1.7.1=py37h89c1867_3
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd3eb1b0_0
  - pyzmq=22.0.1=py37h499b945_0
  - qt=5.9.7=h5867ecd_1
  - rdkit=2020.09.1.0=py37hd50e099_1
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3deb0d_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=py_0
  - setuptools=52.0.0=py37h06a4308_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py37h06a4308_0
  - sniffio=1.2.0=py37h89c1867_1
  - sqlite=3.33.0=h62c20be_0
  - terminado=0.9.2=py37h89c1867_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py37h5e8e339_1
  - traitlets=5.0.5=py_0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.3=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - joblib==1.0.0
    - llvmlite==0.35.0
    - numba==0.52.0
    - pynndescent==0.5.1
    - scikit-learn==0.24.1
    - scipy==1.6.0
    - threadpoolctl==2.1.0
    - umap-learn==0.5.0
    - kaleido
    - ffmpeg-python

